export type HighSchool = {
  name: string;
  kana: string; // 頭文字判定用
};

// 都道府県ごとの高校リスト（進学校・主要校を中心に収録）
export const HIGH_SCHOOLS_BY_PREFECTURE: Record<string, HighSchool[]> = {
  北海道: [
    { name: "札幌北高校", kana: "さ" },
    { name: "札幌南高校", kana: "さ" },
    { name: "札幌東高校", kana: "さ" },
    { name: "札幌西高校", kana: "さ" },
    { name: "札幌旭丘高校", kana: "さ" },
    { name: "北嶺高校", kana: "ほ" },
    { name: "函館中部高校", kana: "は" },
    { name: "旭川東高校", kana: "あ" },
  ],
  青森県: [
    { name: "青森高校", kana: "あ" },
    { name: "弘前高校", kana: "ひ" },
    { name: "八戸高校", kana: "は" },
    { name: "青森県立三本木高校", kana: "あ" },
  ],
  岩手県: [
    { name: "盛岡第一高校", kana: "も" },
    { name: "盛岡第三高校", kana: "も" },
    { name: "岩手高校", kana: "い" },
  ],
  宮城県: [
    { name: "仙台第二高校", kana: "せ" },
    { name: "仙台第一高校", kana: "せ" },
    { name: "仙台青陵中等教育学校", kana: "せ" },
    { name: "宮城第一高校", kana: "み" },
    { name: "東北学院高校", kana: "と" },
  ],
  秋田県: [
    { name: "秋田高校", kana: "あ" },
    { name: "秋田南高校", kana: "あ" },
    { name: "秋田北高校", kana: "あ" },
  ],
  山形県: [
    { name: "山形東高校", kana: "や" },
    { name: "山形南高校", kana: "や" },
    { name: "山形西高校", kana: "や" },
  ],
  福島県: [
    { name: "福島高校", kana: "ふ" },
    { name: "安積高校", kana: "あ" },
    { name: "磐城高校", kana: "い" },
    { name: "郡山高校", kana: "こ" },
  ],
  茨城県: [
    { name: "水戸第一高校", kana: "み" },
    { name: "土浦第一高校", kana: "つ" },
    { name: "竹園高校", kana: "た" },
    { name: "茨城高校", kana: "い" },
    { name: "常総学院高校", kana: "し" },
    { name: "江戸川学園取手高校", kana: "え" },
  ],
  栃木県: [
    { name: "宇都宮高校", kana: "う" },
    { name: "栃木高校", kana: "と" },
    { name: "宇都宮女子高校", kana: "う" },
    { name: "作新学院高校", kana: "さ" },
  ],
  群馬県: [
    { name: "前橋高校", kana: "ま" },
    { name: "高崎高校", kana: "た" },
    { name: "中央中等教育学校", kana: "ち" },
    { name: "太田高校", kana: "お" },
  ],
  埼玉県: [
    { name: "浦和高校", kana: "う" },
    { name: "浦和第一女子高校", kana: "う" },
    { name: "大宮高校", kana: "お" },
    { name: "川越高校", kana: "か" },
    { name: "川越女子高校", kana: "か" },
    { name: "春日部高校", kana: "か" },
    { name: "所沢北高校", kana: "と" },
    { name: "越谷北高校", kana: "こ" },
    { name: "栄東高校", kana: "さ" },
    { name: "開智高校", kana: "か" },
    { name: "大宮開成高校", kana: "お" },
    { name: "昌平高校", kana: "し" },
    { name: "本庄東高校", kana: "ほ" },
    { name: "城北埼玉高校", kana: "し" },
    { name: "慶應義塾志木高校", kana: "け" },
    { name: "早稲田大学本庄高等学院", kana: "わ" },
  ],
  千葉県: [
    { name: "千葉高校", kana: "ち" },
    { name: "東葛飾高校", kana: "ひ" },
    { name: "船橋高校", kana: "ふ" },
    { name: "佐倉高校", kana: "さ" },
    { name: "千葉東高校", kana: "ち" },
    { name: "渋谷教育学園幕張高校", kana: "し" },
    { name: "市川高校", kana: "い" },
    { name: "昭和学院秀英高校", kana: "し" },
    { name: "東邦大学付属東邦高校", kana: "と" },
    { name: "専修大学松戸高校", kana: "せ" },
    { name: "芝浦工業大学柏高校", kana: "し" },
    { name: "麗澤高校", kana: "れ" },
    { name: "日本大学習志野高校", kana: "に" },
  ],
  東京都: [
    { name: "開成高校", kana: "か" },
    { name: "麻布高校", kana: "あ" },
    { name: "武蔵高校", kana: "む" },
    { name: "駒場東邦高校", kana: "こ" },
    { name: "海城高校", kana: "か" },
    { name: "桐朋高校", kana: "と" },
    { name: "城北高校", kana: "し" },
    { name: "巣鴨高校", kana: "す" },
    { name: "本郷高校", kana: "ほ" },
    { name: "芝高校", kana: "し" },
    { name: "早稲田高校", kana: "わ" },
    { name: "早稲田実業学校高等部", kana: "わ" },
    { name: "慶應義塾高校", kana: "け" },
    { name: "慶應義塾女子高校", kana: "け" },
    { name: "桜蔭高校", kana: "お" },
    { name: "女子学院高校", kana: "し" },
    { name: "豊島岡女子学園高校", kana: "と" },
    { name: "雙葉高校", kana: "ふ" },
    { name: "渋谷教育学園渋谷高校", kana: "し" },
    { name: "広尾学園高校", kana: "ひ" },
    { name: "東京都市大学附属高校", kana: "と" },
    { name: "帝京大学高校", kana: "て" },
    { name: "日比谷高校", kana: "ひ" },
    { name: "西高校", kana: "に" },
    { name: "国立高校", kana: "く" },
    { name: "青山高校", kana: "あ" },
    { name: "戸山高校", kana: "と" },
    { name: "新宿高校", kana: "し" },
    { name: "小山台高校", kana: "こ" },
    { name: "八王子東高校", kana: "は" },
    { name: "立川高校", kana: "た" },
    { name: "墨田川高校", kana: "す" },
    { name: "江戸川高校", kana: "え" },
    { name: "明治大学付属明治高校", kana: "め" },
    { name: "中央大学高校", kana: "ち" },
    { name: "中央大学附属高校", kana: "ち" },
    { name: "法政大学高校", kana: "ほ" },
    { name: "立教池袋高校", kana: "り" },
    { name: "青山学院高等部", kana: "あ" },
    { name: "國學院高校", kana: "こ" },
    { name: "錦城高校", kana: "き" },
    { name: "順天高校", kana: "し" },
  ],
  神奈川県: [
    { name: "横浜翠嵐高校", kana: "よ" },
    { name: "湘南高校", kana: "し" },
    { name: "柏陽高校", kana: "か" },
    { name: "厚木高校", kana: "あ" },
    { name: "川和高校", kana: "か" },
    { name: "横浜サイエンスフロンティア高校", kana: "よ" },
    { name: "栄光学園高校", kana: "え" },
    { name: "聖光学院高校", kana: "せ" },
    { name: "浅野高校", kana: "あ" },
    { name: "逗子開成高校", kana: "ず" },
    { name: "神奈川大学附属高校", kana: "か" },
    { name: "山手学院高校", kana: "や" },
    { name: "フェリス女学院高校", kana: "ふ" },
    { name: "横浜雙葉高校", kana: "よ" },
    { name: "桐蔭学園高校", kana: "と" },
    { name: "桐光学園高校", kana: "と" },
    { name: "日本大学高校", kana: "に" },
    { name: "慶應義塾湘南藤沢高校", kana: "け" },
    { name: "中央大学附属横浜高校", kana: "ち" },
    { name: "法政大学第二高校", kana: "ほ" },
  ],
  新潟県: [
    { name: "新潟高校", kana: "に" },
    { name: "新潟南高校", kana: "に" },
    { name: "長岡高校", kana: "な" },
    { name: "新潟明訓高校", kana: "に" },
  ],
  富山県: [
    { name: "富山高校", kana: "と" },
    { name: "富山中部高校", kana: "と" },
    { name: "高岡高校", kana: "た" },
  ],
  石川県: [
    { name: "金沢泉丘高校", kana: "か" },
    { name: "金沢大学附属高校", kana: "か" },
    { name: "金沢高校", kana: "か" },
    { name: "星稜高校", kana: "せ" },
  ],
  福井県: [
    { name: "藤島高校", kana: "ふ" },
    { name: "高志高校", kana: "こ" },
  ],
  山梨県: [
    { name: "甲府南高校", kana: "こ" },
    { name: "甲府第一高校", kana: "こ" },
    { name: "山梨学院高校", kana: "や" },
  ],
  長野県: [
    { name: "長野高校", kana: "な" },
    { name: "松本深志高校", kana: "ま" },
    { name: "上田高校", kana: "う" },
    { name: "諏訪清陵高校", kana: "す" },
  ],
  岐阜県: [
    { name: "岐阜高校", kana: "き" },
    { name: "岐阜北高校", kana: "き" },
    { name: "大垣北高校", kana: "お" },
    { name: "斐太高校", kana: "ひ" },
  ],
  静岡県: [
    { name: "静岡高校", kana: "し" },
    { name: "浜松北高校", kana: "は" },
    { name: "沼津東高校", kana: "ぬ" },
    { name: "磐田南高校", kana: "い" },
    { name: "加藤学園暁秀高校", kana: "か" },
    { name: "静岡雙葉高校", kana: "し" },
  ],
  愛知県: [
    { name: "旭丘高校", kana: "あ" },
    { name: "明和高校", kana: "め" },
    { name: "一宮高校", kana: "い" },
    { name: "岡崎高校", kana: "お" },
    { name: "刈谷高校", kana: "か" },
    { name: "時習館高校", kana: "じ" },
    { name: "東海高校", kana: "と" },
    { name: "南山高校", kana: "な" },
    { name: "滝高校", kana: "た" },
    { name: "愛知高校", kana: "あ" },
    { name: "中京大学附属中京高校", kana: "ち" },
    { name: "愛知工業大学名電高校", kana: "あ" },
  ],
  三重県: [
    { name: "四日市高校", kana: "よ" },
    { name: "津高校", kana: "つ" },
    { name: "伊勢高校", kana: "い" },
    { name: "海星高校", kana: "か" },
  ],
  滋賀県: [
    { name: "膳所高校", kana: "ぜ" },
    { name: "守山高校", kana: "も" },
    { name: "比叡山高校", kana: "ひ" },
  ],
  京都府: [
    { name: "堀川高校", kana: "ほ" },
    { name: "嵯峨野高校", kana: "さ" },
    { name: "洛南高校", kana: "ら" },
    { name: "西京高校", kana: "に" },
    { name: "洛星高校", kana: "ら" },
    { name: "同志社高校", kana: "と" },
    { name: "立命館高校", kana: "り" },
    { name: "立命館宇治高校", kana: "り" },
    { name: "同志社国際高校", kana: "と" },
    { name: "京都女子高校", kana: "き" },
    { name: "花園高校", kana: "は" },
  ],
  大阪府: [
    { name: "北野高校", kana: "き" },
    { name: "天王寺高校", kana: "て" },
    { name: "大阪星光学院高校", kana: "お" },
    { name: "清風南海高校", kana: "せ" },
    { name: "高槻高校", kana: "た" },
    { name: "四天王寺高校", kana: "し" },
    { name: "大阪桐蔭高校", kana: "お" },
    { name: "豊中高校", kana: "と" },
    { name: "三国丘高校", kana: "み" },
    { name: "岸和田高校", kana: "き" },
    { name: "関西大学高校", kana: "か" },
    { name: "関西大学第一高校", kana: "か" },
    { name: "関西学院千里国際高校", kana: "か" },
    { name: "近畿大学附属高校", kana: "き" },
    { name: "初芝立命館高校", kana: "は" },
    { name: "明星高校", kana: "め" },
    { name: "桃山学院高校", kana: "も" },
    { name: "プール学院高校", kana: "ふ" },
  ],
  兵庫県: [
    { name: "神戸高校", kana: "こ" },
    { name: "長田高校", kana: "な" },
    { name: "姫路西高校", kana: "ひ" },
    { name: "兵庫高校", kana: "ひ" },
    { name: "灘高校", kana: "な" },
    { name: "甲陽学院高校", kana: "こ" },
    { name: "六甲学院高校", kana: "ろ" },
    { name: "関西学院高校", kana: "か" },
    { name: "白陵高校", kana: "は" },
    { name: "須磨学園高校", kana: "す" },
    { name: "雲雀丘学園高校", kana: "ひ" },
  ],
  奈良県: [
    { name: "奈良高校", kana: "な" },
    { name: "郡山高校", kana: "こ" },
    { name: "西大和学園高校", kana: "に" },
    { name: "東大寺学園高校", kana: "と" },
    { name: "帝塚山高校", kana: "て" },
  ],
  和歌山県: [
    { name: "桐蔭高校", kana: "と" },
    { name: "向陽高校", kana: "こ" },
    { name: "智辯学園和歌山高校", kana: "ち" },
  ],
  鳥取県: [
    { name: "鳥取西高校", kana: "と" },
    { name: "米子東高校", kana: "よ" },
  ],
  島根県: [
    { name: "松江北高校", kana: "ま" },
    { name: "出雲高校", kana: "い" },
  ],
  岡山県: [
    { name: "岡山操山高校", kana: "お" },
    { name: "岡山朝日高校", kana: "お" },
    { name: "就実高校", kana: "し" },
    { name: "岡山白陵高校", kana: "お" },
  ],
  広島県: [
    { name: "広島大学附属高校", kana: "ひ" },
    { name: "修道高校", kana: "し" },
    { name: "広島学院高校", kana: "ひ" },
    { name: "AICJ高校", kana: "あ" },
    { name: "呉三津田高校", kana: "く" },
  ],
  山口県: [
    { name: "山口高校", kana: "や" },
    { name: "下関西高校", kana: "し" },
    { name: "高川学園高校", kana: "た" },
  ],
  徳島県: [
    { name: "城南高校", kana: "じ" },
    { name: "富岡東高校", kana: "と" },
    { name: "徳島文理高校", kana: "と" },
  ],
  香川県: [
    { name: "高松高校", kana: "た" },
    { name: "三木高校", kana: "み" },
    { name: "大手前丸亀高校", kana: "お" },
  ],
  愛媛県: [
    { name: "松山東高校", kana: "ま" },
    { name: "今治西高校", kana: "い" },
    { name: "愛光高校", kana: "あ" },
  ],
  高知県: [
    { name: "土佐高校", kana: "と" },
    { name: "高知追手前高校", kana: "こ" },
    { name: "土佐塾高校", kana: "と" },
  ],
  福岡県: [
    { name: "修猷館高校", kana: "し" },
    { name: "筑紫丘高校", kana: "ち" },
    { name: "福岡高校", kana: "ふ" },
    { name: "明善高校", kana: "め" },
    { name: "久留米大学附設高校", kana: "く" },
    { name: "西南学院高校", kana: "せ" },
    { name: "福岡大学附属大濠高校", kana: "ふ" },
    { name: "東福岡高校", kana: "ひ" },
    { name: "九州産業大学付属九州高校", kana: "き" },
  ],
  佐賀県: [
    { name: "佐賀西高校", kana: "さ" },
    { name: "弘学館高校", kana: "こ" },
    { name: "早稲田佐賀高校", kana: "わ" },
  ],
  長崎県: [
    { name: "長崎西高校", kana: "な" },
    { name: "諫早高校", kana: "い" },
    { name: "青雲高校", kana: "せ" },
  ],
  熊本県: [
    { name: "熊本高校", kana: "く" },
    { name: "済々黌高校", kana: "せ" },
    { name: "熊本学園大学付属高校", kana: "く" },
    { name: "文徳高校", kana: "ぶ" },
  ],
  大分県: [
    { name: "大分上野丘高校", kana: "お" },
    { name: "大分舞鶴高校", kana: "お" },
    { name: "大分雄城台高校", kana: "お" },
  ],
  宮崎県: [
    { name: "宮崎大宮高校", kana: "み" },
    { name: "宮崎西高校", kana: "み" },
    { name: "宮崎日本大学高校", kana: "み" },
  ],
  鹿児島県: [
    { name: "鶴丸高校", kana: "つ" },
    { name: "甲南高校", kana: "こ" },
    { name: "ラ・サール高校", kana: "ら" },
  ],
  沖縄県: [
    { name: "那覇高校", kana: "な" },
    { name: "開邦高校", kana: "か" },
    { name: "球陽高校", kana: "き" },
    { name: "沖縄尚学高校", kana: "お" },
  ],
};

// 頭文字グループ
export const KANA_ROWS = [
  { label: "あ行", chars: ["あ", "い", "う", "え", "お"] },
  { label: "か行", chars: ["か", "き", "く", "け", "こ"] },
  { label: "さ行", chars: ["さ", "し", "す", "せ", "そ"] },
  { label: "た行", chars: ["た", "ち", "つ", "て", "と"] },
  { label: "な行", chars: ["な", "に", "ぬ", "ね", "の"] },
  { label: "は行", chars: ["は", "ひ", "ふ", "へ", "ほ"] },
  { label: "ま行", chars: ["ま", "み", "む", "め", "も"] },
  { label: "や行", chars: ["や", "ゆ", "よ"] },
  { label: "ら行", chars: ["ら", "り", "る", "れ", "ろ"] },
  { label: "わ行", chars: ["わ"] },
  { label: "ざ行", chars: ["ざ", "じ", "ず", "ぜ", "ぞ"] },
  { label: "だ行", chars: ["だ", "ぢ", "づ", "で", "ど"] },
  { label: "ば行", chars: ["ば", "び", "ぶ", "べ", "ぼ"] },
];

export const PREFECTURES_LIST = Object.keys(HIGH_SCHOOLS_BY_PREFECTURE);
