import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  "https://xmbzpllpjjhaesinlknq.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtYnpwbGxwampoYWVzaW5sa25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NzQ2MDEsImV4cCI6MjA5MzE1MDYwMX0.WgM4Q0zqTqAmFG4uuXjz74IM5TlmNpBZ_-nZta34frc"
);

const SAMPLES = [
  {
    target_university: "早稲田大学", target_faculty: "文化構想学部", result: "合格",
    entered_university: "早稲田大学", entered_faculty: "文化構想学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3夏（7〜8月）", start_deviation: "40〜50",
    study_style: "通塾", juku_name: "河合塾", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3夏引退）",
    prefecture: "東京都", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["国語"], weak_subjects: ["英語"],
    slump: "あった", slump_timing: "高3夏",
    spring_study: "英単語と文法を固めた",
    summer_study: "苦手科目に集中した",
    fall_study: "過去問を始めた",
    final_study: "過去問の解き直し中心",
    tags: ["逆転合格", "部活ガチ勢", "引退後スタート"],
    title: "部活引退後の2ヶ月で一気に伸びた記録",
    hardest_period: "夏の引退直後、英語が全然伸びなかった。9月に思い切って国語と日本史に全振りして、英語は過去問の傾向対策だけにした。それで10〜11月に一気に点数が安定した。",
    what_worked: "過去問を早めに始めた",
    what_failed: "英単語を後回しにした",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "引退してから逆転できた。焦らず自分の強い科目に集中すれば道は開ける。",
    tutor_display_name: "早稲田文化構想の先輩", tutor_gender: "女性",
    author_email: "sample01@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "慶應義塾大学", target_faculty: "経済学部", result: "合格",
    entered_university: "慶應義塾大学", entered_faculty: "経済学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高3春（4〜6月）", start_deviation: "50〜60",
    study_style: "独学", tutoring_cost: "0円",
    daily_study_hours: "9〜12時間", club_activity: "あり（高3春引退）",
    prefecture: "神奈川県", family_support: "普通", economic_pressure: "あった",
    strong_subjects: ["英語", "数学"], weak_subjects: ["現代文"],
    slump: "あった", slump_timing: "高3秋",
    spring_study: "英単語と文法を固めた",
    summer_study: "1日8時間以上勉強した",
    fall_study: "志望校対策に切り替えた",
    final_study: "新しい教材を増やさなかった",
    tags: ["独学", "お金なしで合格", "英語で稼いだ"],
    title: "塾なし・独学で慶應経済に合格した記録",
    hardest_period: "秋の模試で偏差値が5下がった。原因を分析したら過去問をやりすぎて基礎が抜けていた。11月に一度立ち返って基礎固めをしたら直前期に安定した。",
    what_worked: "教材を絞って何周もした",
    what_failed: "過去問開始が遅かった",
    redo_advice: "過去問は夏前から触り始める",
    message: "塾に行けなかったけど独学で受かった。お金がなくても戦略次第で十分戦える。",
    tutor_display_name: "慶應経済の先輩", tutor_gender: "男性",
    author_email: "sample02@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "明治大学", target_faculty: "政治経済学部", result: "合格",
    entered_university: "明治大学", entered_faculty: "政治経済学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3夏（7〜8月）", start_deviation: "〜40",
    study_style: "通塾", juku_name: "武田塾", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3夏引退）",
    prefecture: "埼玉県", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["日本史"], weak_subjects: ["英語", "現代文"],
    slump: "あった", slump_timing: "高3夏",
    summer_study: "苦手科目に集中した",
    fall_study: "弱点ノートを作った",
    final_study: "暗記の穴を潰した",
    tags: ["逆転合格", "E判定から逆転", "夏からスタート"],
    title: "E判定から夏スタートで明治に逆転合格",
    hardest_period: "夏に偏差値40以下で焦って英語に全振りしたが9月になっても伸びなかった。思い切って英語は最低限に絞り、日本史に8割の時間を使ったら10月以降に合計点が急上昇した。",
    what_worked: "苦手科目から逃げなかった",
    what_failed: "英単語を後回しにした",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "夏からでも遅くない。得意科目に全振りする勇気が逆転の鍵だった。",
    tutor_display_name: "明治政経の先輩", tutor_gender: "男性",
    author_email: "sample03@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "上智大学", target_faculty: "外国語学部", result: "合格",
    entered_university: "上智大学", entered_faculty: "外国語学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高3春（4〜6月）", start_deviation: "40〜50",
    study_style: "映像授業", juku_name: "スタディサプリ（映像）", tutoring_cost: "〜30万",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "東京都", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["英語"], weak_subjects: ["国語"],
    slump: "なかった",
    spring_study: "英単語と文法を固めた",
    summer_study: "英語長文を毎日解いた",
    fall_study: "志望校対策に切り替えた",
    final_study: "生活リズムを本番に合わせた",
    english_strategy: "毎日長文を1題解いた",
    tags: ["映像授業のみ", "スタサプのみ", "英語で稼いだ"],
    title: "スタサプだけで上智外語に合格した戦略",
    hardest_period: "9月から毎日英語長文を1題音読する習慣をつけたら、10月末に速読スピードが明らかに変わった。それ以降は長文が苦にならなくなった。",
    what_worked: "毎日同じ時間に勉強した",
    what_failed: "参考書を詰め込みすぎた",
    redo_advice: "スマホ制限を早めにする",
    message: "高い塾代を払わなくてもスタサプで十分戦える。英語は毎日継続が全て。",
    tutor_display_name: "上智外語の先輩", tutor_gender: "女性",
    author_email: "sample04@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "立教大学", target_faculty: "経営学部", result: "合格",
    entered_university: "立教大学", entered_faculty: "経営学部",
    exam_year: "1浪", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "浪人してから", start_deviation: "40〜50",
    study_style: "通塾", juku_name: "河合塾", tutoring_cost: "100万以上",
    daily_study_hours: "9〜12時間", club_activity: "なし",
    prefecture: "東京都", family_support: "普通", economic_pressure: "あった",
    strong_subjects: ["現代文"], weak_subjects: ["英語", "日本史"],
    slump: "あった", slump_timing: "浪人中",
    tags: ["浪人成功", "スランプ脱出"],
    title: "全落ち→浪人→立教経営合格。立て直しの記録",
    hardest_period: "浪人5月の模試でまたE判定が出て崩れかけた。塾の先生に相談したら「弱点だけ潰せ」と言われ、英文法を1冊完璧にすることだけに集中した。6月末から点数が動き始めた。",
    what_worked: "過去問を早めに始めた",
    what_failed: "睡眠を削りすぎた",
    redo_advice: "模試の判定より過去問の手応えを信じる",
    message: "全落ちしても終わりじゃない。浪人して自分の弱点と向き合えたから合格できた。",
    tutor_display_name: "立教経営の先輩（浪人経験）", tutor_gender: "男性",
    author_email: "sample05@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "青山学院大学", target_faculty: "経営学部", result: "合格",
    entered_university: "青山学院大学", entered_faculty: "経営学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3春（4〜6月）", start_deviation: "40〜50",
    study_style: "通塾＋独学", juku_name: "東進ハイスクール", tutoring_cost: "100万以上",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3春引退）",
    prefecture: "神奈川県", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["英語"], weak_subjects: ["日本史"],
    slump: "あった", slump_timing: "高3秋",
    tags: ["部活ガチ勢", "英語で稼いだ", "過去問重視"],
    title: "部活春引退→英語全振り→青学経営合格",
    hardest_period: "秋に日本史の通史が終わらないと気づき焦った。10月から日本史を毎日3時間に増やして、英語を過去問のみに絞った。11月末にギリギリ通史を終わらせて直前期に間に合った。",
    what_worked: "過去問を早めに始めた",
    what_failed: "科目配分を間違えた",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "科目の配分ミスに気づくのが遅かった。秋に気づいて修正できたのがギリギリ間に合った理由。",
    tutor_display_name: "青学経営の先輩", tutor_gender: "女性",
    author_email: "sample06@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "中央大学", target_faculty: "法学部", result: "合格",
    entered_university: "中央大学", entered_faculty: "法学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高2", start_deviation: "50〜60",
    study_style: "独学", tutoring_cost: "0円",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "東京都", family_support: "ほぼなかった", economic_pressure: "あった",
    strong_subjects: ["現代文", "日本史"], weak_subjects: ["英語"],
    slump: "なかった",
    tags: ["独学", "お金なしで合格", "コツコツ型"],
    title: "塾なし独学で中央法合格。お金がなくても戦える",
    hardest_period: "高2の冬に英語だけが全く伸びず、受験を諦めかけた。YouTubeで英文法を全部無料で学んで、英単語は図書館で毎日1時間だけやると決めた。それで高3春に一気に基礎が固まった。",
    what_worked: "毎日同じ時間に勉強した",
    what_failed: "参考書を詰め込みすぎた",
    redo_advice: "過去問は夏前から触り始める",
    message: "お金がなくても絶対に受かる方法はある。図書館とYouTubeで十分戦える。",
    tutor_display_name: "中央法の先輩", tutor_gender: "男性",
    author_email: "sample07@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "法政大学", target_faculty: "経営学部", result: "合格",
    entered_university: "法政大学", entered_faculty: "経営学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3秋以降", start_deviation: "〜40",
    study_style: "通塾", juku_name: "武田塾", tutoring_cost: "30〜100万",
    daily_study_hours: "9〜12時間", club_activity: "あり（高3秋引退）",
    prefecture: "埼玉県", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["英語"], weak_subjects: ["現代文", "日本史"],
    slump: "あった", slump_timing: "高3冬（直前期）",
    tags: ["高3秋からスタート", "短期集中型", "逆転合格"],
    title: "高3秋スタート・短期集中で法政経営合格",
    hardest_period: "10月から本格的に始めて時間が全然足りないと悟った。日本史は諦めて英語と現代文の2科目に絞り、法政の出題形式に特化した演習だけを繰り返した。",
    what_worked: "教材を絞って何周もした",
    what_failed: "過去問開始が遅かった",
    redo_advice: "過去問は夏前から触り始める",
    message: "10月スタートでも受かる。でも科目を絞る決断を早くする必要がある。",
    tutor_display_name: "法政経営の先輩", tutor_gender: "男性",
    author_email: "sample08@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "同志社大学", target_faculty: "経済学部", result: "合格",
    entered_university: "同志社大学", entered_faculty: "経済学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高3春（4〜6月）", start_deviation: "50〜60",
    study_style: "通塾＋独学", juku_name: "河合塾マナビス", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3春引退）",
    prefecture: "大阪府", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["英語", "世界史"], weak_subjects: ["現代文"],
    slump: "なかった",
    tags: ["関関同立対策", "英語で稼いだ", "コツコツ型"],
    title: "関西から同志社経済合格。英語特化の戦略",
    hardest_period: "8月の模試で現代文が全く解けなかった。9月から現代文の解法を固定して、問題のパターン分析に特化した。10月末に急に安定し始めて最終的に安定した得点源になった。",
    what_worked: "毎日同じ時間に勉強した",
    what_failed: "英単語を後回しにした",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "現代文は才能じゃなくて解法。正しい型を覚えれば誰でも安定する。",
    tutor_display_name: "同志社経済の先輩", tutor_gender: "男性",
    author_email: "sample09@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "立命館大学", target_faculty: "法学部", result: "合格",
    entered_university: "立命館大学", entered_faculty: "法学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3夏（7〜8月）", start_deviation: "40〜50",
    study_style: "通塾", juku_name: "東進衛星予備校", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3夏引退）",
    prefecture: "京都府", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["日本史"], weak_subjects: ["英語"],
    slump: "あった", slump_timing: "高3夏",
    tags: ["夏からスタート", "部活ガチ勢", "逆転合格"],
    title: "夏引退→立命館法合格。分岐点は日本史の切り替え",
    hardest_period: "夏に英語の長文が全く読めなくて崩れかけた。塾長に相談したら「英語は捨てるな、でも日本史で点を稼げ」と言われた。秋から日本史を完璧にする方針に変えて、英語は基礎問題だけにした。",
    what_worked: "苦手科目から逃げなかった",
    what_failed: "英単語を後回しにした",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "部活と勉強の両立は辛いけど、引退後の集中力は別物。夏からでも間に合う。",
    tutor_display_name: "立命館法の先輩", tutor_gender: "男性",
    author_email: "sample10@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "早稲田大学", target_faculty: "商学部", result: "合格",
    entered_university: "早稲田大学", entered_faculty: "商学部",
    exam_year: "1浪", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "浪人してから", start_deviation: "50〜60",
    study_style: "通塾", juku_name: "駿台予備校", tutoring_cost: "100万以上",
    daily_study_hours: "9〜12時間", club_activity: "なし",
    prefecture: "東京都", family_support: "普通", economic_pressure: "あった",
    strong_subjects: ["英語", "現代文"], weak_subjects: ["日本史"],
    slump: "あった", slump_timing: "浪人中",
    tags: ["浪人成功", "早慶対策", "英語で稼いだ"],
    title: "現役で早稲田落ち→浪人で早稲田商に合格した記録",
    hardest_period: "浪人の夏、英語の点数は高いのに日本史で足を引っ張り続けた。8月に一念発起して日本史だけを1日4時間に増やした。10月以降に通史が完成して一気に合計点が伸びた。",
    what_worked: "過去問を早めに始めた",
    what_failed: "模試に振り回された",
    redo_advice: "模試の判定より過去問の手応えを信じる",
    message: "浪人は恥じゃない。弱点を徹底的に潰せる一年間だった。",
    tutor_display_name: "早稲田商の先輩（浪人経験）", tutor_gender: "男性",
    author_email: "sample11@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "慶應義塾大学", target_faculty: "商学部", result: "合格",
    entered_university: "慶應義塾大学", entered_faculty: "商学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高2", start_deviation: "50〜60",
    study_style: "通塾＋独学", juku_name: "Z会", tutoring_cost: "〜30万",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "神奈川県", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["英語", "数学"], weak_subjects: ["現代文"],
    slump: "なかった",
    tags: ["コツコツ型", "早慶対策", "朝型"],
    title: "高2から計画的に積み上げて慶應商合格",
    hardest_period: "高3の10月、他の人が過去問をどんどん解いているのに自分だけ基礎が完成していないと気づいた。2週間だけ過去問を止めて英語の弱点をひとつひとつ潰した。その後は過去問が一気に安定した。",
    what_worked: "教材を絞って何周もした",
    what_failed: "演習が足りなかった",
    redo_advice: "過去問は夏前から触り始める",
    message: "計画を立てて着実にやれば慶應も狙える。焦らずコツコツが最強。",
    tutor_display_name: "慶應商の先輩", tutor_gender: "女性",
    author_email: "sample12@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "関西学院大学", target_faculty: "法学部", result: "合格",
    entered_university: "関西学院大学", entered_faculty: "法学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3春（4〜6月）", start_deviation: "40〜50",
    study_style: "通塾", juku_name: "河合塾", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3春引退）",
    prefecture: "兵庫県", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["英語"], weak_subjects: ["現代文", "世界史"],
    slump: "あった", slump_timing: "高3秋",
    tags: ["関関同立対策", "部活ガチ勢"],
    title: "春引退→関学法合格。世界史を捨てた判断",
    hardest_period: "10月に世界史の暗記量に限界を感じた。11月から世界史を捨てて英語と現代文に集中した。関学の出題は英語の配点が高いと分かっていたので英語特化に振り切ったのが正解だった。",
    what_worked: "過去問を早めに始めた",
    what_failed: "科目配分を間違えた",
    redo_advice: "過去問は夏前から触り始める",
    message: "志望校の出題傾向を早く分析すること。それが戦略の全て。",
    tutor_display_name: "関学法の先輩", tutor_gender: "男性",
    author_email: "sample13@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "関西大学", target_faculty: "商学部", result: "合格",
    entered_university: "関西大学", entered_faculty: "商学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "〜45",
    study_start_timing: "高3夏（7〜8月）", start_deviation: "〜40",
    study_style: "通塾", juku_name: "増田塾", tutoring_cost: "30〜100万",
    daily_study_hours: "9〜12時間", club_activity: "あり（高3冬まで）",
    prefecture: "大阪府", family_support: "普通", economic_pressure: "あった",
    strong_subjects: ["英語"], weak_subjects: ["日本史", "現代文"],
    slump: "あった", slump_timing: "高3冬（直前期）",
    tags: ["関関同立対策", "部活ガチ勢", "短期集中型"],
    title: "部活引退2月→関大商合格。ラストスパートの記録",
    hardest_period: "2月まで部活をやっていて受験まで2週間しかなかった。過去問を捨てて、英語の頻出問題パターンだけを丸暗記することにした。範囲を超絞りして集中できたのが合格につながった。",
    what_worked: "教材を絞って何周もした",
    what_failed: "過去問開始が遅かった",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "2週間でも受かる。でもそのためには完全に絞り込む決断が必要。",
    tutor_display_name: "関大商の先輩", tutor_gender: "男性",
    author_email: "sample14@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "早稲田大学", target_faculty: "法学部", result: "不合格",
    entered_university: "明治大学", entered_faculty: "法学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高3春（4〜6月）", start_deviation: "50〜60",
    study_style: "通塾", juku_name: "河合塾", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "東京都", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["英語"], weak_subjects: ["現代文"],
    slump: "あった", slump_timing: "高3秋",
    tags: ["全落ち経験あり", "併願戦略が甘かった", "早慶対策"],
    title: "早稲田法に落ちて明治法へ。誤算を全部書く",
    hardest_period: "11月の早稲田過去問で合格点に全く届かず、このまま落ちると確信した。でも方向転換できずに早稲田対策を続けてしまった。もっと早くMARCHに重点を切り替えるべきだった。",
    what_worked: "過去問を早めに始めた",
    what_failed: "併願戦略が甘かった",
    redo_advice: "模試の判定より過去問の手応えを信じる",
    message: "落ちた経験も後輩の役に立つ。早稲田に届かなかった理由を全部書いた。",
    tutor_display_name: "明治法の先輩（早稲田不合格経験）", tutor_gender: "男性",
    author_email: "sample15@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "慶應義塾大学", target_faculty: "文学部", result: "合格",
    entered_university: "慶應義塾大学", entered_faculty: "文学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高3春（4〜6月）", start_deviation: "50〜60",
    study_style: "独学", tutoring_cost: "0円",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "神奈川県", family_support: "普通", economic_pressure: "あった",
    strong_subjects: ["現代文", "英語"], weak_subjects: ["日本史"],
    slump: "なかった",
    tags: ["独学", "お金なしで合格", "国語で稼いだ"],
    title: "塾なし・文系独学で慶應文学部に合格",
    hardest_period: "日本史の文化史が直前まで手つかずだった。1月から文化史だけを1日2時間集中して、他の範囲は切り捨てた。慶應文の出題傾向から文化史の配点が高いと分かっていたので的中した。",
    what_worked: "過去問を早めに始めた",
    what_failed: "参考書を詰め込みすぎた",
    redo_advice: "過去問は夏前から触り始める",
    message: "慶應は傾向対策が全て。過去問分析を徹底すれば独学でも合格できる。",
    tutor_display_name: "慶應文の先輩", tutor_gender: "女性",
    author_email: "sample16@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "明治大学", target_faculty: "商学部", result: "合格",
    entered_university: "明治大学", entered_faculty: "商学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3夏（7〜8月）", start_deviation: "40〜50",
    study_style: "通塾＋独学", juku_name: "東進ハイスクール", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3夏引退）",
    prefecture: "千葉県", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["日本史"], weak_subjects: ["英語", "現代文"],
    slump: "あった", slump_timing: "高3夏",
    tags: ["夏からスタート", "部活ガチ勢", "MARCH対策"],
    title: "夏引退・スマホ断ちで明治商合格",
    hardest_period: "引退直後にスマホを見る時間が全然減らなかった。8月中旬に親にスマホを預けて1ヶ月完全断ち。勉強時間が1日3時間から8時間に増えて、9月の模試で偏差値が一気に10上がった。",
    what_worked: "毎日同じ時間に勉強した",
    what_failed: "スマホ時間を減らすのが遅かった",
    redo_advice: "スマホ制限を早めにする",
    message: "スマホを親に預けた1ヶ月が全てを変えた。自分への強制力が大事。",
    tutor_display_name: "明治商の先輩", tutor_gender: "男性",
    author_email: "sample17@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "立教大学", target_faculty: "社会学部", result: "合格",
    entered_university: "立教大学", entered_faculty: "社会学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3春（4〜6月）", start_deviation: "40〜50",
    study_style: "映像授業", juku_name: "河合塾マナビス", tutoring_cost: "30〜100万",
    daily_study_hours: "3〜6時間", club_activity: "あり（高3春引退）",
    prefecture: "埼玉県", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["現代文"], weak_subjects: ["英語"],
    slump: "あった", slump_timing: "高3夏",
    tags: ["MARCH対策", "国語で稼いだ", "部活ガチ勢"],
    title: "現代文で稼ぐ戦略で立教社学合格",
    hardest_period: "英語が伸びず夏にパニックになった。担任に相談したら「現代文と日本史で逃げ切れる大学を選べ」とアドバイスされた。立教の配点を調べて現代文特化に切り替えたのが正解だった。",
    what_worked: "苦手科目から逃げなかった",
    what_failed: "英単語を後回しにした",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "英語が苦手でも現代文で稼ぐ戦略がある。志望校の配点分析が先決。",
    tutor_display_name: "立教社学の先輩", tutor_gender: "女性",
    author_email: "sample18@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "早稲田大学", target_faculty: "社会科学部", result: "合格",
    entered_university: "早稲田大学", entered_faculty: "社会科学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高2", start_deviation: "40〜50",
    study_style: "通塾＋独学", juku_name: "早稲田塾", tutoring_cost: "100万以上",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "東京都", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["英語", "日本史"], weak_subjects: ["現代文"],
    slump: "あった", slump_timing: "高3秋",
    tags: ["早慶対策", "英語で稼いだ", "過去問重視"],
    title: "高2から早稲田社学を狙った2年間の記録",
    hardest_period: "高3の10月、社学の過去問を初めて解いたら現代文で半分以下しか取れなかった。11月から現代文の解法を固定して、社学特有の問題形式だけに特化した演習を繰り返した。",
    what_worked: "過去問を早めに始めた",
    what_failed: "演習が足りなかった",
    redo_advice: "過去問は夏前から触り始める",
    message: "早稲田社学は現代文が難しい。過去問に早く慣れた人が有利。",
    tutor_display_name: "早稲田社学の先輩", tutor_gender: "男性",
    author_email: "sample19@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "青山学院大学", target_faculty: "国際政治経済学部", result: "合格",
    entered_university: "青山学院大学", entered_faculty: "国際政治経済学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高3春（4〜6月）", start_deviation: "50〜60",
    study_style: "通塾", juku_name: "河合塾", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "東京都", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["英語"], weak_subjects: ["日本史"],
    slump: "なかった",
    tags: ["英語で稼いだ", "MARCH対策", "女性の先輩"],
    title: "英語で逃げ切る戦略で青学国際政経合格",
    hardest_period: "日本史の演習問題で秋になっても合格点が取れなかった。10月に過去問を分析したら英語の配点が全体の50%超えていたので、日本史の時間を削って英語演習を倍にした。本番は英語で逃げ切れた。",
    what_worked: "過去問を早めに始めた",
    what_failed: "科目配分を間違えた",
    redo_advice: "過去問は夏前から触り始める",
    message: "青学国際は英語命。配点を見て科目配分を決めることが全て。",
    tutor_display_name: "青学国際政経の先輩", tutor_gender: "女性",
    author_email: "sample20@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "同志社大学", target_faculty: "法学部", result: "合格",
    entered_university: "同志社大学", entered_faculty: "法学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高2", start_deviation: "50〜60",
    study_style: "通塾", juku_name: "駿台予備校", tutoring_cost: "100万以上",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "京都府", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["英語", "現代文"], weak_subjects: ["世界史"],
    slump: "あった", slump_timing: "高3夏",
    tags: ["関関同立対策", "コツコツ型"],
    title: "世界史の壁を乗り越えて同志社法合格",
    hardest_period: "夏に世界史の暗記量に圧倒されて崩れかけた。8月に世界史を地域ごとに分割して、1週間で1地域を完璧にする方法に切り替えた。9月末に全地域が終わって急速に安定した。",
    what_worked: "教材を絞って何周もした",
    what_failed: "参考書を詰め込みすぎた",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "世界史は地域ごとに区切ると急に整理される。全部一気にやろうとしないこと。",
    tutor_display_name: "同志社法の先輩", tutor_gender: "男性",
    author_email: "sample21@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "明治大学", target_faculty: "情報コミュニケーション学部", result: "合格",
    entered_university: "明治大学", entered_faculty: "情報コミュニケーション学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3春（4〜6月）", start_deviation: "40〜50",
    study_style: "独学", tutoring_cost: "0円",
    daily_study_hours: "3〜6時間", club_activity: "あり（高3春引退）",
    prefecture: "神奈川県", family_support: "ほぼなかった", economic_pressure: "あった",
    strong_subjects: ["現代文"], weak_subjects: ["英語", "日本史"],
    slump: "あった", slump_timing: "高3夏",
    tags: ["独学", "お金なしで合格", "スランプ脱出"],
    title: "経済的事情で塾なし→明治情コミュ合格",
    hardest_period: "夏に偏差値が全く動かず、塾にも行けない状況で諦めかけた。YouTubeで現代文の解法動画を毎日1本見てノートにまとめるだけを2ヶ月続けた。10月に急に点数が安定し始めた。",
    what_worked: "毎日同じ時間に勉強した",
    what_failed: "スマホ時間を減らすのが遅かった",
    redo_advice: "スマホ制限を早めにする",
    message: "お金がなくても工夫次第で十分戦える。継続できれば必ず伸びる。",
    tutor_display_name: "明治情コミュの先輩", tutor_gender: "男性",
    author_email: "sample22@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "法政大学", target_faculty: "法学部", result: "合格",
    entered_university: "法政大学", entered_faculty: "法学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3夏（7〜8月）", start_deviation: "40〜50",
    study_style: "通塾", juku_name: "武田塾", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3秋引退）",
    prefecture: "東京都", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["英語"], weak_subjects: ["現代文"],
    slump: "なかった",
    tags: ["夏からスタート", "MARCH対策", "部活ガチ勢"],
    title: "秋引退→3ヶ月で法政法合格した記録",
    hardest_period: "10月に引退して残り4ヶ月しかなかった。過去問を解いたら現代文が壊滅的だった。現代文だけに絞って毎日1問解法通りに解く練習を繰り返した。12月末に安定して年明けは自信を持って臨めた。",
    what_worked: "教材を絞って何周もした",
    what_failed: "過去問開始が遅かった",
    redo_advice: "過去問は夏前から触り始める",
    message: "引退から3ヶ月で合格できる。でも毎日の質と量が全て。",
    tutor_display_name: "法政法の先輩", tutor_gender: "女性",
    author_email: "sample23@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "関西学院大学", target_faculty: "経済学部", result: "合格",
    entered_university: "関西学院大学", entered_faculty: "経済学部",
    exam_year: "1浪", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "浪人してから", start_deviation: "40〜50",
    study_style: "通塾", juku_name: "河合塾", tutoring_cost: "100万以上",
    daily_study_hours: "9〜12時間", club_activity: "なし",
    prefecture: "兵庫県", family_support: "手厚かった", economic_pressure: "あった",
    strong_subjects: ["英語"], weak_subjects: ["現代文", "世界史"],
    slump: "あった", slump_timing: "浪人中",
    tags: ["浪人成功", "関関同立対策", "スランプ脱出"],
    title: "浪人で関学経済合格。スランプ脱出の分岐点",
    hardest_period: "浪人7月に模試の判定が全部E判定で精神的に崩れた。1週間勉強を完全に止めて旅行した。リフレッシュして戻ったら逆に集中力が上がって、8月から過去問中心に切り替えたら秋に一気に伸びた。",
    what_worked: "毎日同じ時間に勉強した",
    what_failed: "睡眠を削りすぎた",
    redo_advice: "模試の判定より過去問の手応えを信じる",
    message: "メンタルが崩れたら一度完全に休む勇気も必要。それが浪人の分岐点だった。",
    tutor_display_name: "関学経済の先輩（浪人経験）", tutor_gender: "男性",
    author_email: "sample24@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "立命館大学", target_faculty: "経営学部", result: "合格",
    entered_university: "立命館大学", entered_faculty: "経営学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3春（4〜6月）", start_deviation: "40〜50",
    study_style: "映像授業", juku_name: "スタディサプリ（映像）", tutoring_cost: "〜30万",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "京都府", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["英語", "現代文"], weak_subjects: ["世界史"],
    slump: "なかった",
    tags: ["スタサプのみ", "映像授業のみ", "関関同立対策"],
    title: "スタサプのみで立命館経営合格。コスパ最強の勉強法",
    hardest_period: "世界史の量に圧倒されて秋に諦めかけた。立命館の過去問を分析したら世界史は暗記より因果関係の理解問題が多いと分かった。丸暗記をやめて流れを理解する勉強に切り替えたら本番で解けた。",
    what_worked: "過去問を早めに始めた",
    what_failed: "参考書を詰め込みすぎた",
    redo_advice: "過去問は夏前から触り始める",
    message: "スタサプは使い方次第で十分戦える。大事なのは継続と志望校分析。",
    tutor_display_name: "立命館経営の先輩", tutor_gender: "男性",
    author_email: "sample25@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "上智大学", target_faculty: "経済学部", result: "合格",
    entered_university: "上智大学", entered_faculty: "経済学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高3春（4〜6月）", start_deviation: "50〜60",
    study_style: "通塾", juku_name: "河合塾", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "東京都", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["英語", "数学"], weak_subjects: ["現代文"],
    slump: "あった", slump_timing: "高3秋",
    tags: ["早慶対策", "英語で稼いだ", "数学受験"],
    title: "数学・英語型で上智経済合格。文系に数学は武器になる",
    hardest_period: "秋に現代文が壊滅的な点数で焦った。上智の配点を調べたら英語と数学で80%を占めると分かった。現代文の勉強時間を週2時間に減らして英語と数学だけに集中した。本番は現代文を捨てて合格した。",
    what_worked: "過去問を早めに始めた",
    what_failed: "科目配分を間違えた",
    redo_advice: "過去問は夏前から触り始める",
    message: "文系でも数学で受けると有利な大学がある。配点を早く調べること。",
    tutor_display_name: "上智経済の先輩", tutor_gender: "男性",
    author_email: "sample26@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "中央大学", target_faculty: "商学部", result: "合格",
    entered_university: "中央大学", entered_faculty: "商学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "〜45",
    study_start_timing: "高3夏（7〜8月）", start_deviation: "〜40",
    study_style: "通塾", juku_name: "東進ハイスクール", tutoring_cost: "30〜100万",
    daily_study_hours: "9〜12時間", club_activity: "あり（高3夏引退）",
    prefecture: "千葉県", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["日本史"], weak_subjects: ["英語", "現代文"],
    slump: "あった", slump_timing: "高3夏",
    tags: ["夏からスタート", "逆転合格", "MARCH対策"],
    title: "偏差値40以下から夏スタートで中央商合格",
    hardest_period: "夏に偏差値40以下の状態で本格スタート。日本史は得意だったので日本史を最高得点に仕上げ、英語は単語と文法の基礎だけに絞った。捨てる勇気が合格の分岐点だった。",
    what_worked: "苦手科目から逃げなかった",
    what_failed: "英単語を後回しにした",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "偏差値40でも夏から始めれば間に合う。でも得意科目への全振りが必要。",
    tutor_display_name: "中央商の先輩", tutor_gender: "男性",
    author_email: "sample27@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "早稲田大学", target_faculty: "教育学部", result: "合格",
    entered_university: "早稲田大学", entered_faculty: "教育学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "55〜65",
    study_start_timing: "高3春（4〜6月）", start_deviation: "50〜60",
    study_style: "独学", tutoring_cost: "0円",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "埼玉県", family_support: "ほぼなかった", economic_pressure: "あった",
    strong_subjects: ["日本史", "現代文"], weak_subjects: ["英語"],
    slump: "あった", slump_timing: "高3夏",
    tags: ["独学", "お金なしで合格", "国語で稼いだ"],
    title: "塾なし・経済的困難を乗り越えて早稲田教育合格",
    hardest_period: "英語が夏になっても全く伸びず、塾なしで不安が爆発した。8月に英語を最低限に絞り、日本史と現代文だけで早稲田教育の合格点を取る逆算をした。日本史満点を目標にして実際に本番で満点近くを取れた。",
    what_worked: "過去問を早めに始めた",
    what_failed: "英単語を後回しにした",
    redo_advice: "高2のうちに英単語だけ固める",
    message: "お金がなくても、英語が苦手でも、得意科目で補える大学はある。諦めないで。",
    tutor_display_name: "早稲田教育の先輩", tutor_gender: "女性",
    author_email: "sample28@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "関西大学", target_faculty: "法学部", result: "合格",
    entered_university: "関西大学", entered_faculty: "法学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "45〜55",
    study_start_timing: "高3春（4〜6月）", start_deviation: "40〜50",
    study_style: "通塾＋独学", juku_name: "河合塾マナビス", tutoring_cost: "30〜100万",
    daily_study_hours: "6〜9時間", club_activity: "あり（高3春引退）",
    prefecture: "大阪府", family_support: "普通", economic_pressure: "なかった",
    strong_subjects: ["英語"], weak_subjects: ["国語"],
    slump: "なかった",
    tags: ["関関同立対策", "部活ガチ勢", "英語で稼いだ"],
    title: "春引退→英語特化で関大法合格",
    hardest_period: "現代文が全く安定せず秋になってもずっと足を引っ張っていた。11月に現代文を諦めて英語と世界史だけに絞った。関大の英語はマーク式なので時間配分を最適化したら本番で高得点が取れた。",
    what_worked: "過去問を早めに始めた",
    what_failed: "科目配分を間違えた",
    redo_advice: "過去問は夏前から触り始める",
    message: "現代文が苦手でも英語と社会で逃げ切れる。志望校の形式を徹底分析して。",
    tutor_display_name: "関大法の先輩", tutor_gender: "女性",
    author_email: "sample29@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
  {
    target_university: "慶應義塾大学", target_faculty: "総合政策学部", result: "合格",
    entered_university: "慶應義塾大学", entered_faculty: "総合政策学部",
    exam_year: "現役", bunkei_rikei: "文系", high_school_deviation: "65〜",
    study_start_timing: "高2", start_deviation: "60〜70",
    study_style: "通塾＋独学", juku_name: "河合塾", tutoring_cost: "100万以上",
    daily_study_hours: "6〜9時間", club_activity: "なし",
    prefecture: "東京都", family_support: "手厚かった", economic_pressure: "なかった",
    strong_subjects: ["英語", "現代文"], weak_subjects: [],
    slump: "あった", slump_timing: "高3秋",
    tags: ["早慶対策", "英語で稼いだ", "コツコツ型"],
    title: "慶應SFC合格。英語と小論文だけで戦う特殊戦略",
    hardest_period: "SFCは英語と小論文だけの試験。秋に小論文が全く書けなくて崩れた。毎日1本時事ネタの小論文を書いて先生に添削してもらうことを11月まで続けた。量をこなすことで急速に上達した。",
    what_worked: "毎日同じ時間に勉強した",
    what_failed: "演習が足りなかった",
    redo_advice: "過去問は夏前から触り始める",
    message: "SFCは英語と小論文だけ。特殊な戦略が必要だけど武器にもなる。",
    tutor_display_name: "慶應SFCの先輩", tutor_gender: "男性",
    author_email: "sample30@senpailink.jp",
    tutor_verification_status: "sample", is_published: true,
  },
];

async function seed() {
  console.log(`Inserting ${SAMPLES.length} sample records...`);
  const { data, error } = await supabase.from("experiences").insert(SAMPLES).select("id");
  if (error) {
    console.error("Error:", error.message);
  } else {
    console.log(`✓ Inserted ${data.length} records`);
  }
}

seed();
